In [1]:
# 레이블 인코딩
from sklearn.preprocessing import LabelEncoder
items = ['TV','냉장고','전자레인지','컴퓨터','TV','컴퓨터','냉장고','레고']

encoder = LabelEncoder()
encoder.fit(items) # LabelEncoder().fit(items)
labels = encoder.transform(items)

print('인코딩 변환값:',labels)
print('인코딩 클래스:', encoder.classes_)

인코딩 변환값: [0 1 3 4 0 4 1 2]
인코딩 클래스: ['TV' '냉장고' '레고' '전자레인지' '컴퓨터']


In [2]:
# 레이블 디코딩
origins = encoder.inverse_transform([0,1,2,3,0,1,3,3])
print('디코딩 값:', origins)

디코딩 값: ['TV' '냉장고' '레고' '전자레인지' 'TV' '냉장고' '전자레인지' '전자레인지']


In [3]:
# One Hot Encoding 
from sklearn.preprocessing import OneHotEncoder
import numpy as np

labels=labels.reshape(-1,1)

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels= oh_encoder.transform(labels)

print('원 핫 인코딩 데이터')
print(oh_labels.toarray())
print('원 핫 인코딩 데이터 차원')
print(oh_labels.shape)

원 핫 인코딩 데이터
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
원 핫 인코딩 데이터 차원
(8, 5)


In [4]:
# 판다스의 원 핫 인코딩 / 명목형 데이터를 숫자형으로 변환 필요 없이 바로 2차원 데이터 인코딩 가능 함수
# get_dummies 함수

import pandas as pd
item_df = pd.DataFrame({'item': items})
pd.get_dummies(item_df)

item_TV  item_냉장고  item_레고  item_전자레인지  item_컴퓨터
0        1         0        0           0         0
1        0         1        0           0         0
2        0         0        0           1         0
3        0         0        0           0         1
4        1         0        0           0         0
5        0         0        0           0         1
6        0         1        0           0         0
7        0         0        1           0         0

In [7]:
# iris 데이터의 내재된 분포와 특징 / 타입 / 키 등을 확인
iris = load_iris()
print('붓꽃 데이터세트 타임:', type(iris))

keys = iris.keys()
print('붓꽃 데이터세트 키:' , keys)

#values= iris.values()
#print('붓꽃 데이터세트 값:' , values)

붓꽃 데이터세트 타임: <class 'sklearn.utils.Bunch'>
붓꽃 데이터세트 키: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [6]:
from sklearn.datasets import load_iris
import pandas as pd

iris=load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print(iris_df)

print('feature들의 평균 값: ', iris_df.mean())
print('feature들의 분산 값:', iris_df.var())

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]
feature들의 평균 값:  sepal length (cm)    5.

In [14]:
# 표준화 시켜주기 Scaling
# 표준화를 시켜주면 데이터 값은 -1과 1 사이의 값을 가지게 된다.
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print(iris_df_scaled)
print('feature들의 평균 값:', iris_df_scaled.mean())
print('feature들의 분산 값:', iris_df_scaled.var())

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]
feature들의 평균 값: sepal length (cm)   -1.6

In [16]:
# 최대- 최소 정규화

from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled= pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('feature들의 최소 값:', iris_df_scaled.min())
print('feature들의 최대 값:', iris_df_scaled.max())

feature들의 최소 값: sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature들의 최대 값: sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [25]:
# 스케일링 주의사항 예시
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array=np.arange(0,11).reshape(-1,1)
test_array=np.arange(0,11).reshape(-1,1)

scaler=MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터' , np.round(train_array.reshape(-1),2))
print('Scaled train array 데이터:', np.round(train_scaled.reshape(-1),2))

scaler.fit(test_array)
test_scaled = scaler.transform(test_array)

print('원본 test_array 데이터' , np.round(test_array.reshape(-1),2))

print('Scaled test array 데이터:', np.round(test_scaled.reshape(-1),2))

원본 train_array 데이터 [ 0  1  2  3  4  5  6  7  8  9 10]
Scaled train array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
원본 test_array 데이터 [ 0  1  2  3  4  5  6  7  8  9 10]
Scaled test array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
